version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/php:8.0

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy_app:
    executor: heroku/default
    parameters:
      run-migrations:
        type: boolean
        default: true
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      - when:
          condition: << parameters.run-migrations >>
          steps:
            - run:
                command: |
                  heroku run --app=${HEROKU_APP_NAME} php artisan migrate:fresh
      - run:
          command: |
            heroku --version
workflows:
  deploy:
    jobs:
      - build
      - deploy_app:
          run-migrations: false
